# Generated by Django 5.1.1 on 2024-09-16 07:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_sortie', models.DateField(default=datetime.datetime(2024, 9, 16, 7, 56, 33, 30156, tzinfo=datetime.timezone.utc))),
                ('realisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='realisateur.realisateur')),
            ],
        ),
    ]
