# Generated by Django 5.1.1 on 2024-09-16 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
