# Generated by Django 5.1.1 on 2024-09-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_film_date_sortie'),
        ('realisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='realisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='films', to='realisateur.realisateur'),
        ),
    ]
